version: "3"
services:
  test:
    build:
      context: .
    command: /bin/sh -c "composer install && vendor/bin/phpstan --memory-limit=-1 && vendor/bin/phpunit"
    volumes:
      - .:/project:delegated
    depends_on:
      - emulator
  emulator:
    image: gcr.io/cloud-spanner-emulator/emulator
