<?php

/**
 * Copyright 2019 Colopl Inc. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

declare(strict_types=1);

namespace Colopl\Spanner\Queue;

use Colopl\Spanner\Eloquent\Concerns\InterleaveKeySupport;

/**
 * Implemented by a job that knows the interleave keys of the queue it is
 * dispatched to.
 *
 * These are the same interleave keys that an Eloquent model declares in its
 * `$interleaveKeys` property: the key columns a row inherits from the table it
 * is interleaved into.
 *
 * A dispatched job object is serialized into an opaque blob inside the payload,
 * so the driver cannot find the values there. It asks the job instead, before
 * the payload is built.
 *
 * ```
 * class ProcessUserTask implements ShouldQueue, ProvidesInterleaveKeys
 * {
 *     public function __construct(private User $user) {}
 *
 *     public function getInterleaveKeys(): array
 *     {
 *         return ['UserId' => $this->user->getKey()];
 *     }
 * }
 * ```
 */
interface ProvidesInterleaveKeys
{
    /**
     * A value for each of the queue's interleave keys, keyed by column name.
     *
     * Careful: this returns values, `['UserId' => 'a-user-id']`, while the
     * identically named {@see SpannerQueue::getInterleaveKeys()} and
     * {@see InterleaveKeySupport::getInterleaveKeys()} return the column names
     * alone, `['UserId']`.
     *
     * `MessageId` is generated by the driver and must not be included here.
     *
     * @return array<string, scalar>
     */
    public function getInterleaveKeys(): array;
}
